sitephoto/blogs/urls.py
from django.conf.urls import patterns, url
from django.views.generic import ListView, DetailView
from .models import Blogs
#
urlpatterns = patterns('',
  url(r'^$', ListView.as_view(
    model=Item,
    context_object_name='albums',
    template_name='album.html'),
    name='gallery'
    ),
  url(r'^(?P<slug>[\w-]+)/$', DetailView.as_view(
    model=Item,
    context_object_name='photos',
    template_name='photo.html'),
    name='photos'
    ),
)

sitephoto/contact/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
   # url(r'^$','contact.views.contact', name='contact'),
    url(r'^$', 'contact.views.add_contact', name='add_contact'),
)
                

sitephoto/sitephoto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from galery.views import photo_list, show_photo
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import ListView
from galery.models import Slider, Video
from galery import views as views_slider
from contact import views as views_contact
from comment import views as views_comment
from blogs import views 
from blogs.models import Blogs
from uslugi import views as views_uslugi
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views_slider.slider_main, name="slider_main"),
    url(r'^uslugi/', views_uslugi.show_uslugi, name='show_uslugi'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^blog/', views.news, name='blog'), 
    url(r'^comments/',views_comment.comments, name='comments'),
   # url(r'^galery/$', photo_list, name='photo_list'),
   # url(r'^galery/(?P<slug>[\w-]+)/$', show_photo, name='show_photo'),
    url(r'^galery/', include('galery.urls')),
    url(r'^contact/', views_contact.contact, name='contact'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^projects/view/(\d+)/', views.project_detail, name='project_detail'),
    url(r'^video/$', ListView.as_view(
    model=Video,
    context_object_name='videos',
    template_name='video.html'),
    name='video'
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitephoto/blogs/models.py
from django.db import models
from django.conf import settings
from django.db.models.fields.files import ImageField, ImageFieldFile
from embed_video.fields import EmbedVideoField
from ckeditor_uploader.fields import RichTextUploadingField
import PIL
from PIL import Image
import os
from os import path
from django.core.urlresolvers import reverse


class Blogs(models.Model):
    def __str__(self):
        return self.title

    def get_absolute_url(self):     
        return reverse('project_detail', args=[self.id])

    def get_thumbnail(self):
        return self.img.url
    
    title = models.CharField("Название новости", max_length=60)
    publish_date = models.DateTimeField("Publish Date", auto_now_add=True)
    #content = models.TextField("Описание")
    news = models.TextField("Новость:")
    img = models.ImageField("Изображение",null=False, blank=False, upload_to='Albums')
    content = RichTextUploadingField(blank=True, default='', config_name='awesome_ckeditor')

sitephoto/comment/models.py
from django.db import models


class Comment(models.Model):
    name = models.CharField("Имя",max_length=200)
    photo = models.FileField("Фотография",blank=False, upload_to='Albums')
    email = models.EmailField("Email")
    message = models.TextField("Ваш отзыв")
    date = models.DateTimeField(auto_now=True)
    check = models.BooleanField("Отображать отзыв",default=False)


    class Meta:
        ordering = ['date']
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'
	
    def __str__(self):
        return (self.name)

sitephoto/contact/models.py
from django.db import models



class Orders(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField("Email")
    message=models.TextField("Сообщение")

    class Meta:
        ordering = ['name']
        verbose_name='Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return(self.name)

sitephoto/galery/models.py
from django.db import models
from django.conf import settings
from django.db.models.fields.files import ImageField, ImageFieldFile
from embed_video.fields import EmbedVideoField
from ckeditor_uploader.fields import RichTextUploadingField
import PIL
from PIL import Image
import os
from os import path
from django.core.urlresolvers import reverse

_MAX_SIZE = 500
	
class Item(models.Model):
    title = models.CharField("Название альбома",max_length=200)
    description = models.TextField("Описание")
    img = models.ImageField("Изображение альбома",null=False, blank=False, upload_to='Albums')
    slug = models.SlugField("Ссылка для альбома",max_length=100)
	
    class Meta:
        ordering = ['title']
        verbose_name = 'Альбом'
        verbose_name_plural = 'Альбомы'
	
    def __str__(self):
        return (self.title)

		
class Photo(models.Model):
	item = models.ForeignKey(Item, verbose_name=u'Альбом')
	title = models.CharField("Название фотографии",max_length=100)
	img = models.ImageField("Фото", upload_to='Photos')

	
	class Meta:
		verbose_name = 'Фото'
		verbose_name_plural = 'Фотографии'
		
	def __str__(self):
		return self.title
		
		
	def image_img(self):
            image_path = os.path.join(settings.MEDIA_URL, self.img)
            image_path = image_path.replace('\\','/')
            return '<a href="'+ str(self.id)+'/"><img src="'+str(image_path) +'"/></a>'

            image_img.short_description = 'Картинка'
            image_img.allow_tags = True




class Slider(models.Model):
	image = models.ImageField("Фото на слайдер",)
	title = models.CharField("Название фото-слайдера",max_length=40)
	class Meta:
		verbose_name = 'Фото на слайдер'
		verbose_name_plural = 'Фотографии на слайдер'
	
	def __str__(self):
		return self.title
		
class Video(models.Model):
	title = models.CharField("Название видео",max_length=50)
	video = EmbedVideoField(blank=True, verbose_name='Видео')
	

sitephoto/uslugi/models.py
from django.db import models



class uslugi_photo(models.Model):
	title = models.CharField("Название фото-услуги", max_length=200)
	description = models.TextField("Описание")

	class Meta:
		ordering = ['title']
		verbose_name = 'Фото-услуга'
		verbose_name_plural = 'Фото-услуги'
	def __str__(self):
		return(self.title)

class uslugi_video(models.Model):
	title = models.CharField("Название видео-услуги", max_length=200)
	description = models.TextField("Описание")

	class Meta:
		ordering = ['title']
		verbose_name = 'Видео-услуга'
		verbose_name_plural = ['Видео-услуги']
	def __str__(self):
		return(self.title)

sitephoto/comment/forms.py
from django import forms
from captcha.fields import CaptchaField

class CommentForm(forms.Form):
    name = forms.CharField(max_length=50,label='', widget=forms.TextInput(attrs={'class':'form-control','placeholder': 'Ваше ИМЯ'}), error_messages={'required': 'Введите Ваше имя'})
    email =  forms.EmailField(label='', widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'Ваше Email'}),error_messages={'required': 'Введите Ваш email'})  
    message = forms.CharField(label='', widget=forms.Textarea(attrs={'class': 'form-control text', 'placeholder':'Ваш отзыв'}),error_messages={'required': 'Введите Ваш отзыв'})
    photo = forms.FileField(label='', error_messages={'required': 'Выберите фотографию'})
    captcha = CaptchaField(label='Введите код с картинки:', error_messages={'required': 'Неверный код'})
    

sitephoto/contact/forms.py
from django import forms
from captcha.fields import CaptchaField

class ContactForm(forms.Form):
    name = forms.CharField(max_length=50,label='', widget=forms.TextInput(attrs={'class':'form-control','placeholder': 'Ваше ИМЯ'}),error_messages={'required': 'Введите Ваше имя'})
    email =  forms.EmailField(label='', widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'Ваше Email для связи'}),error_messages={'required': 'Введите Ваш Email'})
    #number_phone = forms.CharField(max_length=50)
    message = forms.CharField(label='', widget=forms.Textarea(attrs={'class': 'form-control text', 'placeholder':'Ваше сообщение'}),error_messages={'required': 'Введите сообщение'})
    captcha = CaptchaField(label='Введите код с картинки:', error_messages={'required': 'Неверный код'})
    

sitephoto/blogs/views.py
from django.shortcuts import render
from .models import *
# Create your views here

def news(request):
    recent_blogs = Blogs.objects.all().order_by('-publish_date')
    context = {'blogs': recent_blogs,}
    #import pdb; pdb.set_trace()
    return render(request, 'blog.html', context)


def project_detail(request, project_id):
    project_object = Blogs.objects.filter(id=project_id)
    project_object = project_object[0] 
    #import pdb; pdb.set_trace()
    context = {
        'project': project_object,
    }
    return render(request, 'project_detail.html', context)

sitephoto/comment/views.py
from django.shortcuts import render
from .models import *
from comment.forms import *

def comments(request):
	recent_comments = Comment.objects.filter(check=True).order_by('-date')
	#context = {'comments': recent_comments,}
	if request.method == 'POST':
		#import pdb; pdb.set_trace()
		form = CommentForm(request.POST,request.FILES)
		if form.is_valid():
			load=True
			import pdb; pdb.set_trace()
			comments = Comment(name=form.cleaned_data['name'], email=form.cleaned_data['email'],message=form.cleaned_data['message'],photo=request.FILES['photo'])
			#import pdb; pdb.set_trace()
			comments.save()
			form=CommentForm()
		else:
			load=False
	else:
		load=True
		form = CommentForm()
	return render(request, 'comments.html', {'comments':recent_comments,'form':form,'load':load})

sitephoto/contact/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from contact.forms import *
from contact.models import Orders
from django.shortcuts import render_to_response


def contact(request):
        all_is_right=''
        if request.method == 'POST':
                form = ContactForm(request.POST)
                if form.is_valid():
                        #import pdb; pdb.set_trace()
                        orders = Orders(name=form.cleaned_data['name'], email=form.cleaned_data['email'], message=form.cleaned_data['message'])
                        orders.save()
                        all_is_right ="Ваше сообщение успешно отправлено"
                        form = ContactForm()
        else:
                form = ContactForm()

        return render(request, 'contact.html', {'form':form, 'all_is_right': all_is_right,})

sitephoto/uslugi/views.py
from django.shortcuts import render
from .models import*

def show_uslugi(request):
    #import pdb; pdb.set_trace()
    photos_uslugi = uslugi_photo.objects.all()
    videos_uslugi = uslugi_video.objects.all()
    #import pdb; pdb.set_trace()
    context={
        "photos_uslugi":photos_uslugi,
        "videos_uslugi":videos_uslugi,
        }
    #import pdb; pdb.set_trace()
    return render(request, 'uslugi.html', context)

sitephoto/templates/album.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}
{% block content %}
{% load staticfiles %}

<div class="head_post" > 
    <div class="container">
      <div class="row">      
        <div class="col-md-12 col-sm-12" id="portfolio_content" style="padding-right:0px;padding-left:0px;">
			      <div class="row-flex">
			      {% for album in albums %}
              <div class="col-md-4 col-sm-6 col-xs-12" style="padding-left:0px; padding-right:0px;">
                <div class="hover ehover13">		
                    <a href='{{album.slug}}'>	
					          <img class="img-responsive" src='{{album.img.url}}' >
					          <div class="overlay">
                    <h2>{{album.title}}</h2>
                    <button class="info nullbutton" data-toggle="modal" data-target="#modal13">Просмотр</button>
                    </div>
					          </a>                    
                  </div>                     
                </div>      
			      {% endfor %}
			      </div>
          </div>          
        </div>
      </div>
    </div>


<div class="light-wrapper nullstyle " style="background: #f2f2f2; border-top: 1px solid rgba(0, 0, 0, 0.09)" >
  <div class="container inner">
    <div class="row">
      <div id="aq-block-939-30" class="aq-block aq-block-aq_section_title_block col-sm-12 aq-first ">
        <div class="swiper-wrapper flickr-wrapper"> 
          <div class="swiper-container flickr">
            <div class="swiper flickr-feed"> 
              <div class="aq-block aq-block-aq_ebor_text_block col-sm-12">
                  <h3 align="center"> Портфолио фотографа – отличная возможность ознакомиться с уровнем его профессионализма</h3>

                  <p class="p18">Каждый профессиональный фотограф, ну или человек, стремящийся к этому почетному «званию» должен предоставить своим клиентам возможность детально ознакомиться со своими предыдущими работами, а также с такими их аспектами как качество,тематика, разнообразность, подбор ракурсов, подбор декораций, грима и так далее. Мы очень тщательно подходим к организации своего портфолио, чтобы представленные в нем фото максимально отображали индивидуальное видение фотографа своих кадров. 
                  </p> 
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>




{% endblock %}

sitephoto/templates/base.html
<!DOCTYPE HTML>
<html>
	<head>
		<title>Главная - {% block title%}{% endblock %}</title>
		
		{% load staticfiles %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>    
		<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/accordion.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.lazyload.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/eskju.jquery.scrollflow.js' %}"></script>


        <link rel="stylesheet" type="text/css" href="{% static 'css/effects.css' %}">

		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-social.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" /> 
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/1.css' %}">


		
	

	</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><img src="{% static 'images/brand1.png' %}"></a>
        </div>
    <div class="navbar-collapse collapse">

    <ul class="nav navbar-nav navbar-right">
        <li><a title="Главная" href="/">Главная</a></li>
        <li><a title="Портфолио" href="/galery">Портфолио</a></li>
        <li><a title="Услуги" href="/uslugi">Услуги</a></li>
        <li><a title="Блог" href="/blog">Блог</a></li>
        <li><a title="Видео" href="/video">Видео</a></li>
        <li><a title="Отзывы" href="/comments">Отзывы</a></li>
        <li><a title="Контакты" href="/contact">Контакты</a></li>
    </ul>
  
    </div>
	</div>
</div>
	{% block content %}{% endblock %}

<div class="footer black-wrapper widget-footer">
    <div class="container inner">
        <div class="row">
            <div class="col-sm-6">
                <div id="text-3">
                    <span class="fixh3_2" style="color: #cacaca">О нас</span>
                    <div class="textwidget" style="color: #cacaca">
                        <p>Студия фотографии предлагает вам услуги команды фотографов, видеографов ведущих Премиум класса.</p>
                        <p>Работая с нашей командой, вы сможете переживать эти воспоминания изо дня в день.</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <span class="fixh3_2" style="color: #cacaca">КАК НАС НАЙТИ</span>
                <div class="textwidget" style="color: #cacaca">
                        <p>По вопросам связанными с услугами фотографа, видеографа свяжитесь с нами одним из способов:</p>
                </div>
               
                <div class="icon" style="color: #cacaca"> 
                    <i class="glyphicon glyphicon-earphone" style="font-size:20px; margin-right: 10px;"></i>   +7 906 417 90 32 <br> 
                    <i class="glyphicon glyphicon-envelope" style="font-size:20px; margin-right: 10px;"></i>   2404822@rambler.ru <br> 
                </div> 
            </div>
        </div>
    </div>
</div>
<div class="sub-footer">
    <div class="container"> 
        <div class="pull-left">
             <p style="color: #cacaca">© 2016 BULENKOV.PRO</p>
        </div>
        <ul class="social pull-right">
            <li><a class="btn btn-social-icon btn-sm btn-vk" href="http://vk.com/lerochka017"><span class="fa fa-vk"></span></a></li>
            <li><a class="btn btn-social-icon btn-sm btn-facebook"><span class="fa fa-facebook"></span></a></li>
            <li><a class="btn btn-social-icon btn-sm btn-odnoklassniki"><span class="fa fa-odnoklassniki"></span></a></li>
            <li><a class="btn btn-social-icon btn-sm btn-vimeo"><span class="fa fa-vimeo"></span></a></li>
        </ul>	    
    </div>
</div>		
</body>
</html>

sitephoto/templates/blog.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}
{% block content %}
{% load staticfiles %}
{% load thumbnail %}
<script type="text/javascript"> 
/*
$(document).ready(function(){
        var highestBox = 0;
        $('.bbb', this).each(function(){
          if($(this).height() > highestBox) {
                highestBox = $(this).height();
            }
        });
        $('.bbb',this).height(highestBox);
    });




</script>
<div class="head_post">
    <br/>
    <div class="container">
        <div class="row">
            {% for project in blogs %}

<div class=" col-xs-12 col-sm-6 col-md-4 col-lg-4 events"> 
<div style="height:200px;">
<img class="img-responsive" style="height=100%; width: 100%; object-fit: cover;" src="{{project.get_thumbnail}}"></div>
          <div class="desc" style="background-color: #FFF">
          <div style="height:70px;">
            <h4><a href="{{project.get_absolute_url}}">{{project.title}}</a></h4>
            </div>
            <p style=" overflow:hidden; display: -webkit-box;
   line-height: 16px;     /* fallback */    /* fallback */
   -webkit-line-clamp: 6; /* number of lines to show */
   -webkit-box-orient: vertical;">{{project.news}}</p>
   <a href="{{project.get_absolute_url}}">Читать далее...</a>
          </div>
        </div>


            {% endfor %}
        </div>
        <br/> 
        <br/>
    </div>
</div>



{% endblock %}

sitephoto/templates/blog_list.html
{% load static %}

{% for project_triplet in blogs %}
<div class="head_post">
<br/>
	<div class="container">
		<div class="row">
    		{% for project in project_triplet %}
    		<div class="col-lg-12">
        		<h2>{{project.title}}</h2></a>
        		<p>{{project.content | safe}}</p>
    		</div>
    		{% endfor %}
		</div>
	</div>
</div>
{% endfor %}

sitephoto/templates/comments.html
{% extends "base.html" %}

{% block title %}Comments{% endblock %}
{% block content %}
{% load staticfiles %}
{% load thumbnail %}



<div class="head_post" style="border-bottom: 1px solid rgba(0, 0, 0, 0.09)">
<br/>




    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2 style="text-align:center;"> Видео блог – это лицо каждого современного фотографа</h2>
                <br>
                <p class="p18"> Мой видеоблог был создан для размещения самых актуальных на данный момент времени видеоотчетов с различных мастер-классов, поездок с фотосессиями за границу, а также бэкстейджей со съемочных площадок. </p>
                <br>
            </div>
        </div>
    </div>
</div>


<div class="container">
<div class="row">
    {% for comment in comments %}
    <div class="col-lg-12 cl-md-12 col-sm-12 col-xs-12 comment" style="float:left; ">
        <div class="row">
        <div class="col-sm-3 col-sm-offset-1 col-md-3 col-md-3-offset-1 col-lg-3 col-lg-offset-1 col-xs-6 col-xs-offset-3">
        <img class="img-responsive img-circle" src='{{comment.photo.url}}'  >
        </div>
        <div class="col-sm-7 col-sm-offset-1 col-md-7 col-md-offset-1 col-lg-7 col-lg-offset-1 col-xs-12">
        <h2 style="margin-top: 20px; font-family: 'Tahoma', serif; color: #444;">{{comment.name}}</h2>
        <h3 style="font-style: italic; color: #999; font-size: 16px; line-height: 1;font-weight: 400;">{{comment.date}}</h3>
        <p class="com_p">{{comment.message}}</p>
        </div>
        </div>
    </div>
    {% endfor %}
</div>
<br/> 
<div class="container">

<button class="btn btn-info btn-lg tex1 btn-block" type="button" data-toggle="modal" data-target="#myModal" align="center">Оставить отзыв</button>
</div>
<br/>

</div>

   
<div class="container">
    <div class="alert alert-success hidden" id="success-alert">
        <h2>Успех</h2>
        <div>Ваши данные были успешно отправлены.</div>
    </div>
 
</div>


{% if load == False %}
<div class="te1"></div>
{% endif %}


<div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button class="close" type="button" data-dismiss="modal">×</button>
                <h4 class="modal-title">Оставить отзыв</h4>
            </div>

            <div class="modal-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }} 
                <div class="modal-footer">
                <input type="submit" class="btn btn-submit col-md-offset-2">
                </div>
            </form> 
            </div>
            
        </div>
    </div>
</div>


<script type="text/javascript">
if ($(".te1").length!=0){
    $(".tex1").click();
}
</script>
{% endblock %}

sitephoto/templates/contact.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}
{% block content %}
{% load staticfiles %}
{% load thumbnail %}




<div class="light-wrapper">
<div class="otstup">
	<div class="container">
	<div class="row">
	<div class="col-lg-8 col-sm-8">
	    <h3 style="text-align: center; font-size: 16pt;
	    padding-bottom: 15px;">СВЯЖИТЕСЬ С НАМИ ЧЕРЕЗ ФОРМУ ОБРАТНОЙ СВЯЗИ</h3>
		<p class="p18" style="text-align: center; padding-bottom: 11px;">Задайте свои вопросы нам и не забудьте указать свои контактные данные</p>
		<h4>{% if all_is_right %}{{ all_is_right }}{% endif %}</h4>
		<form action="{% url 'contact' %}" method="post">
		{% csrf_token %}
		{{ form }} 
		
		<button class="btn btn-info btn-lg tex1 btn-block" input type="submit" style="margin-top: 10px;"> Отправить </button>
		
		</form>	
	</div>
	<div class="col-lg-4 col-sm-4">
		<h3 style="text-align: center; font-size: 16pt; padding-bottom: 15px; padding-top: 15px;">КОНТАКТЫ</h3>
		<p class="p18" style="text-align: center;">Большое спасибо, что проявили интерес к моим работам!</p>
		<p class="p18" style="text-align: center; padding-bottom: 11px;">Чтобы заказать фотосессию или узнать о свободных датах, свяжитесь со мной по контактам, указанным ниже.</p>
		<div class="icon"> 
             <p class="p18"> <i class="glyphicon glyphicon-earphone" style="font-size:20px; margin-right: 10px; margin-left:30px; "></i> +7 906 417 90 32 </p>
            <p class="p18"> <i class="glyphicon glyphicon-envelope" style="font-size:20px; margin-right: 10px; margin-left:30px;"></i>  2404822@rambler.ru </p>
        </div> 
       
        <p class="p18" style="text-align: center;">Мои странички в соц.сетях:</p>
        <div style="text-align: center;">
          	<a class="btn btn-social-icon btn-xs btn-vk" href="http://vk.com/lerochka017"><span class="fa fa-vk"></span></a>
  			<a class="btn btn-social-icon btn-xs btn-facebook"><span class="fa fa-facebook"></span></a>
			<a class="btn btn-social-icon btn-xs btn-odnoklassniki"><span class="fa fa-odnoklassniki"></span></a>
			<a class="btn btn-social-icon btn-xs btn-vimeo"><span class="fa fa-vimeo"></span></a>
		</div>
	</div>
</div>
</div>
</div>
</div>
{% endblock %}

sitephoto/templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}
{% block content %}

<h2>Welcome to the Gallary!</h3>

<table>
	<tr>
		{% for album in albums %}
		{% if album.title_photo%}
			<td>
			<h1>{{album.name}}<h1/>
			<img src="{{album.title_photo.url}}"/>

		{%endif%}		
			</td>
		{% endfor %}
	</tr>
</table>

{% endblock %}

sitephoto/templates/items_detail.html
{% extends "base.html" %}

{% block title %}{{object.name}}{% endblock %}

{% block content %}

<p><a href="{% url item_list %}">&laquo; Back to full listing</a></p>
<h2>{{object.name}}</h2>
<p>{{object.description}}</p>

<h3>Photos</h3>
<table>
	<tr>
		<th>Title</tr>
		<th>Thumbnail</th>
		<th>Caption</th>
	</tr>
	{% for photo in object.photo_set.all %}
	<tr>
		<td><i>{{photo.title}}</i></td>
		<td>
			<a href="{{photo.get_image_thumb_url}}">
				<img src="{{photo.get_image_thumb_url}}" />
			</a>
		</td>
		<td>{{photo.caption}}</td>
	</tr>
	{% endfor %}
</table>
{% endblock %}

			

sitephoto/templates/photo.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}
{% block content %}
{% load staticfiles %}
{% load thumbnail %}



<div class="head_post">
<div class="container" style="max-width:1000px;">		
<div class="row">
<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">

{% if photos.photo_set.all %}
<h2 style="text-align: center;">{{photos.title}}</h2>
<p class="p18">{{photos.description}}</p>
{%endif%}
<br/>

<ul id="photos_block" class="basic-gallery text-center">
{% for photo in photos.photo_set.all %}
	<li>
	<img src='{{photo.img.url}}' class="star">
	</li>
{%endfor%}
</ul>
</div>
</div>
</div>
</div>
  <script type="text/javascript">
function showImages(el) { 
var windowHeight = jQuery( window ).height(); 
$(el).each(function(){ 
var thisPos = $(this).offset().top; 

var topOfWindow = $(window).scrollTop(); 
if (topOfWindow + windowHeight - 200 > thisPos ) { 
$(this).addClass("fadeIn"); 
} 
}); 
} 

$(document).ready(function(){ 
showImages('.star'); 
}); 


$(window).scroll(function() { 
showImages('.star'); 
});
  </script>
{% endblock %}

sitephoto/templates/photo_detail.html
{% extends "base.html" %}

{% block title %}{{object.item.name}} - {{object.title}}{% endblock %}

{% block content %}

<a href="{{ object.item.get_absolute_url }}">&laquo; Back to {{object.item.name}} detail page</a>
<h2>{{object.item.name}} - {{object.title}}</h2>
<img src="{{object.get_image_url}}" />
{% if object.caption %}<p>{{object.caption}}</p>{% endif %}
{% endblock %}